Algoritmo "Exercicio-06"

// 6) Escreva um algoritmo para ler as dimensões de um retângulo
// (base e altura), calcular e escrever a área do retângulo.

Var

base, altura, area : inteiro

Inicio

escreval("Calcular a area de um retangulo")
escreval("Digite a base do retangulo:")
leia(base)

escreval("Digite a altura do retangulo:")
leia(altura)

area := base * altura
escreval("A area do retangulo e",area," metros quadrados")


Fimalgoritmo